### PR TITLE
init

### PR DESCRIPTION
**Pull request by nkozyra**

### CODE REVIEW

**Comment by seangibat** [comment]
:astonished: Good job!

**Comment by foxhipinion** [comment]
lol awesome

**Comment by nkozyra** [comment]
you can literally post there now, eat some dogfood with me

https://hipin.io/forums/better-boarding/simvvzpv-cmon-guys-eat-this-dog-food-with-me

**Comment by natgaertner** [comment]
Error 1062: Duplicate entry '' for key 'phone'

**Comment by nkozyra** [comment]
since you're too good to associate your phone # you can now skip it

**Comment by natgaertner** [comment]
I simply love to associate phone numbers but there is no phone number field on the form.
Anyway yes registration works for me now.

**Comment by nkozyra** [comment]
i will approve ur account for posting then

**Pull request merged**
